export const browserCoreExamples = [
  "openmehdi browser status",
  "openmehdi browser start",
  "openmehdi browser stop",
  "openmehdi browser tabs",
  "openmehdi browser open https://example.com",
  "openmehdi browser focus abcd1234",
  "openmehdi browser close abcd1234",
  "openmehdi browser screenshot",
  "openmehdi browser screenshot --full-page",
  "openmehdi browser screenshot --ref 12",
  "openmehdi browser snapshot",
  "openmehdi browser snapshot --format aria --limit 200",
  "openmehdi browser snapshot --efficient",
  "openmehdi browser snapshot --labels",
];

export const browserActionExamples = [
  "openmehdi browser navigate https://example.com",
  "openmehdi browser resize 1280 720",
  "openmehdi browser click 12 --double",
  'openmehdi browser type 23 "hello" --submit',
  "openmehdi browser press Enter",
  "openmehdi browser hover 44",
  "openmehdi browser drag 10 11",
  "openmehdi browser select 9 OptionA OptionB",
  "openmehdi browser upload /tmp/openmehdi/uploads/file.pdf",
  'openmehdi browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "openmehdi browser dialog --accept",
  'openmehdi browser wait --text "Done"',
  "openmehdi browser evaluate --fn '(el) => el.textContent' --ref 7",
  "openmehdi browser console --level error",
  "openmehdi browser pdf",
];
